// The Android Gradle Plugin builds the native code with the Android NDK.

group = "com.codexgao.xlog_flutter"
version = "1.0"

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath("com.android.tools.build:gradle:8.1.0")
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: "com.android.library"

android {
    if (project.android.hasProperty("namespace")) {
        namespace = "com.codexgao.xlog_flutter"
    }

    compileSdk = 34

    ndkVersion = android.ndkVersion

    defaultConfig {
        minSdk = 21

        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86_64'
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
}

// Build instructions:
//   cd mars/xlog
//   # Release (stripped .so + .debug symbols)
//   python build_android.py --config Release --output-dir ../../samples/xlog_flutter/android/src/main/jniLibs --arch armeabi-v7a arm64-v8a
//   # Debug (unstripped .so)
//   python build_android.py --config Debug --output-dir ../../samples/xlog_flutter/android/src/debug/jniLibs --arch armeabi-v7a arm64-v8a
